{
	portfolio(accountSegments: $account_segment_id, portfolioType: "$portfolio_type") {
		portfolioPositions {
			percentNAV {
				value {
					quantity
				}
			}
			positions {
				 accountings {
					accountingDate
					orderAction
					confirmation {
						confirmationStatus
						volume {
							quantity
						}
					}
				}
			}
			positionType
			currency {
                iso4217Code
            }
			rateable {
				name
				assetClassLiteral
				symbol(type: "ISIN") {
					identifier
				}
				... on BOND {
					dateOfIssue
				}
			}
		}
	}
}
